# Generated by Django 3.0.2 on 2020-01-31 21:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estate', '0002_auto_20200131_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='search_location',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
