# Generated by Django 3.0.2 on 2020-01-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estate', '0003_auto_20200131_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
