# Generated by Django 3.0.2 on 2020-01-31 22:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estate', '0006_auto_20200131_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(location='/root/PycharmProjects/Morgan/Morgan/media'), upload_to=''),
        ),
    ]
