# Generated by Django 3.0.2 on 2020-02-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estate', '0007_auto_20200131_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_distance',
            field=models.PositiveIntegerField(blank=True, max_length=3, null=True),
        ),
    ]
