# Generated by Django 3.0.2 on 2020-02-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estate', '0008_profile_search_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='search_distance',
            field=models.PositiveIntegerField(blank=True, help_text='kilometer', null=True),
        ),
    ]
