# Generated by Django 3.0.2 on 2020-02-01 17:43

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estate', '0009_auto_20200201_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ip_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='realestate',
            name='heating',
            field=models.CharField(choices=[('cirkó', 'Gáz(cirkó)'), ('központi', 'Központi')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='level',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='room',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='room_half',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='size_garden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(), srid=4326),
        ),
        migrations.CreateModel(
            name='RealEstateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/root/PycharmProjects/Morgan/Morgan/media'), upload_to='')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='Estate.RealEstate')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
