# Generated by Django 3.0.2 on 2020-02-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estate', '0010_auto_20200201_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestateimage',
            old_name='file',
            new_name='images',
        ),
    ]
