# Generated by Django 3.0.2 on 2020-02-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estate', '0014_realestate_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='favorite',
        ),
        migrations.AddField(
            model_name='realestate',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='profile_favorites', to='Estate.Profile'),
        ),
    ]
