# Generated by Django 3.0.2 on 2020-02-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estate', '0016_remove_realestate_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False, null=True)),
                ('to_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estate.Profile')),
                ('what', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estate.RealEstate')),
            ],
        ),
    ]
