# Generated by Django 3.0.2 on 2020-02-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estate', '0017_liked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liked',
            unique_together={('what', 'to_who')},
        ),
    ]
